Seperates the range bearing messages into two separate entities.
osrf/lrauv pull request #183
Opened 2022-03-29 02:47 UTC by arjo129

Previously we were using the same RangeBearing message for both external communication and internal communication. This leads to lots of confusion as we were using the same message in two different places. This PR also changes the public facing `LRAUVRangeBearingResponse` to stop using a vector to store the coordinates, but rather explicitly label the coordinates.

Signed-off-by: Arjo Chakravarty <arjo@openrobotics.org>

2022-03-29 03:05 UTC, braanan requested changes

2022-03-29 03:05 UTC, braanan commented on lrauv_ignition_plugins/proto/lrauv_range_bearing_response.proto
> +  /// \brief elevation in radians
`/// \brief vehicle referenced elevation in radians`

2022-03-29 03:05 UTC, braanan commented on lrauv_ignition_plugins/proto/lrauv_range_bearing_response.proto
> +  /// \brief azimuth in radians
`/// \brief vehicle referenced azimuth in radians`

2022-03-29 03:05 UTC, braanan commented on lrauv_ignition_plugins/proto/lrauv_range_bearing_response.proto
> +  double range = 5;
@arjo129 replace with actual time-of-flight in seconds. We could also consider publishing the speed of sound through water that was used for this solution (fixed now, but could be calculated based on water density in the future)

2022-03-29 03:05 UTC, braanan commented on lrauv_ignition_plugins/proto/lrauv_range_bearing_response.proto
>    uint32 req_id = 1;
I think this message should also contain the local and remote addresses

2022-09-09 07:49 UTC, arjo129 commented
Closing as acoustic comms is now working.

2022-09-09 07:49 UTC, closed without merging